language: android
android:
  components:
    # Specify the components that are needed to build the project.
    # 'tools' is listed twice on purpose (to get the newest version).
    - tools
    - platform-tools
    - tools

    # Build tools & SDK.
    - build-tools-26.0.0
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository


before_cache:
  # Clean up the cache.
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fR $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.android/build-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
